In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from config import gkey

In [4]:
fire_census_df = pd.read_csv('data/fire_census.csv')
fire_census_df.head(2)

,Lat,Lng,TOTAL LOSS,PERCENTAGE LOSS,Latitude,Longitude,Accuracy Score,Accuracy Type,Number,Street,...,Census Block Group,Full FIPS (block),Full FIPS (tract),Metro/Micro Statistical Area Name,Metro/Micro Statistical Area Code,Metro/Micro Statistical Area Type,Combined Statistical Area Name,Combined Statistical Area Code,Metropolitan Division Area Name,Metropolitan Division Area Code
0,32.732107,-96.814783,5000,3.01,32.732076,-96.814820,1.0,rooftop,1325.0,S Marsalis Ave,...,2,481130054002017,48113005400,"Dallas-Fort Worth-Arlington, TX",19100,metropolitan,"Dallas-Fort Worth, TX-OK",206,"Dallas-Plano-Irving, TX",19124
1,32.894248,-96.857108,10000,1.87,32.894224,-96.857101,1.0,rooftop,10728.0,Lathrop Dr,...,2,481130097022004,48113009702,"Dallas-Fort Worth-Arlington, TX",19100,metropolitan,"Dallas-Fort Worth, TX-OK",206,"Dallas-Plano-Irving, TX",19124

In [5]:
print(fire_census_df.columns)

Index(['Lat', 'Lng', 'TOTAL LOSS', 'PERCENTAGE LOSS', 'Latitude', 'Longitude',
       'Accuracy Score', 'Accuracy Type', 'Number', 'Street', 'Unit Type',
       'Unit Number', 'City', 'State', 'County', 'Zip', 'Country', 'Source',
       'ACS Economics/Number of households/Total/Value',
       'ACS Economics/Number of households/Total/Margin of error',
       'ACS Economics/Median household income/Total/Value',
       'ACS Economics/Median household income/Total/Margin of error',
       'ACS Economics/Household income/Less than $10,000/Value',
       'ACS Economics/Household income/Less than $10,000/Margin of error',
       'ACS Economics/Household income/Less than $10,000/Percentage',
       'ACS Economics/Household income/$10,000 to $14,999/Value',
       'ACS Economics/Household income/$10,000 to $14,999/Margin of error',
       'ACS Economics/Household income/$10,000 to $14,999/Percentage',
       'ACS Economics/Household income/$15,000 to $19,999/Value',
       'ACS Economics/Household income/$15,000 to $19,999/Margin of error',
       'ACS Economics/Household income/$15,000 to $19,999/Percentage',
       'ACS Economics/Household income/$20,000 to $24,999/Value',
       'ACS Economics/Household income/$20,000 to $24,999/Margin of error',
       'ACS Economics/Household income/$20,000 to $24,999/Percentage',
       'ACS Economics/Household income/$25,000 to $29,999/Value',
       'ACS Economics/Household income/$25,000 to $29,999/Margin of error',
       'ACS Economics/Household income/$25,000 to $29,999/Percentage',
       'ACS Economics/Household income/$30,000 to $34,999/Value',
       'ACS Economics/Household income/$30,000 to $34,999/Margin of error',
       'ACS Economics/Household income/$30,000 to $34,999/Percentage',
       'ACS Economics/Household income/$35,000 to $39,999/Value',
       'ACS Economics/Household income/$35,000 to $39,999/Margin of error',
       'ACS Economics/Household income/$35,000 to $39,999/Percentage',
       'ACS Economics/Household income/$40,000 to $44,999/Value',
       'ACS Economics/Household income/$40,000 to $44,999/Margin of error',
       'ACS Economics/Household income/$40,000 to $44,999/Percentage',
       'ACS Economics/Household income/$45,000 to $49,999/Value',
       'ACS Economics/Household income/$45,000 to $49,999/Margin of error',
       'ACS Economics/Household income/$45,000 to $49,999/Percentage',
       'ACS Economics/Household income/$50,000 to $59,999/Value',
       'ACS Economics/Household income/$50,000 to $59,999/Margin of error',
       'ACS Economics/Household income/$50,000 to $59,999/Percentage',
       'ACS Economics/Household income/$60,000 to $74,999/Value',
       'ACS Economics/Household income/$60,000 to $74,999/Margin of error',
       'ACS Economics/Household income/$60,000 to $74,999/Percentage',
       'ACS Economics/Household income/$75,000 to $99,999/Value',
       'ACS Economics/Household income/$75,000 to $99,999/Margin of error',
       'ACS Economics/Household income/$75,000 to $99,999/Percentage',
       'ACS Economics/Household income/$100,000 to $124,999/Value',
       'ACS Economics/Household income/$100,000 to $124,999/Margin of error',
       'ACS Economics/Household income/$100,000 to $124,999/Percentage',
       'ACS Economics/Household income/$125,000 to $149,999/Value',
       'ACS Economics/Household income/$125,000 to $149,999/Margin of error',
       'ACS Economics/Household income/$125,000 to $149,999/Percentage',
       'ACS Economics/Household income/$150,000 to $199,999/Value',
       'ACS Economics/Household income/$150,000 to $199,999/Margin of error',
       'ACS Economics/Household income/$150,000 to $199,999/Percentage',
       'ACS Economics/Household income/$200,000 or more/Value',
       'ACS Economics/Household income/$200,000 or more/Margin of error',
       'ACS Economics/Household income/$200,000 or more/Percentage',
       'Census Year', 'State FIPS', 'County FIPS', 'Place Name', 'Place FIPS',
       'Census Tract Code', 'Census Block Code', 'Census Block Group',
       'Full FIPS (block)', 'Full FIPS (tract)',
       'Metro/Micro Statistical Area Name',
       'Metro/Micro Statistical Area Code',
       'Metro/Micro Statistical Area Type', 'Combined Statistical Area Name',
       'Combined Statistical Area Code', 'Metropolitan Division Area Name',
       'Metropolitan Division Area Code'],
      dtype='object')

In [6]:
filter_example = fire_census_df.filter(like="Percentage")
filter_example.head()

,"ACS Economics/Household income/Less than $10,000/Percentage","ACS Economics/Household income/$10,000 to $14,999/Percentage","ACS Economics/Household income/$15,000 to $19,999/Percentage","ACS Economics/Household income/$20,000 to $24,999/Percentage","ACS Economics/Household income/$25,000 to $29,999/Percentage","ACS Economics/Household income/$30,000 to $34,999/Percentage","ACS Economics/Household income/$35,000 to $39,999/Percentage","ACS Economics/Household income/$40,000 to $44,999/Percentage","ACS Economics/Household income/$45,000 to $49,999/Percentage","ACS Economics/Household income/$50,000 to $59,999/Percentage","ACS Economics/Household income/$60,000 to $74,999/Percentage","ACS Economics/Household income/$75,000 to $99,999/Percentage","ACS Economics/Household income/$100,000 to $124,999/Percentage","ACS Economics/Household income/$125,000 to $149,999/Percentage","ACS Economics/Household income/$150,000 to $199,999/Percentage","ACS Economics/Household income/$200,000 or more/Percentage"
0,0.127,0.090,0.122,0.062,0.011,0.076,0.110,0.000,0.017,0.046,0.032,0.205,0.034,0.010,0.000,0.058
1,0.026,0.009,0.013,0.017,0.065,0.017,0.008,0.020,0.008,0.026,0.041,0.134,0.178,0.077,0.115,0.246
2,0.139,0.056,0.085,0.021,0.098,0.086,0.078,0.082,0.103,0.049,0.046,0.127,0.022,0.000,0.010,0.000
3,0.114,0.000,0.000,0.044,0.000,0.000,0.223,0.000,0.126,0.112,0.033,0.000,0.135,0.121,0.000,0.093
4,0.036,0.112,0.063,0.030,0.080,0.059,0.000,0.059,0.040,0.228,0.084,0.118,0.036,0.017,0.017,0.021